version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    ports:
        - "4000:5000"
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
